### ISSUE TITLE
Account failed to login 3 times.

### ISSUE THREAD

**Issue by Pinheadsk8r** [PokeAlert/PokeAlert#143]
[logcat_1473973635722.txt](https://github.com/PokeAlert/PokeAlert/files/475628/logcat_1473973635722.txt)
[logcat_1473973555450.txt](https://github.com/PokeAlert/PokeAlert/files/475629/logcat_1473973555450.txt)
[logcat_1473972659196.txt](https://github.com/PokeAlert/PokeAlert/files/475630/logcat_1473972659196.txt)
[logcat_1473972646472.txt](https://github.com/PokeAlert/PokeAlert/files/475633/logcat_1473972646472.txt)
![20160915_142928](https://cloud.githubusercontent.com/assets/22226428/18568297/70fd4718-7b51-11e6-9dd6-f104b48aa9bf.png)

**Comment by PokeAlert** [comment]
09-15 14:03:26.388 32405  6765 W System.err: Caused by: java.net.UnknownHostException: Unable to resolve host "sso.pokemon.com": No address associated with hostname

error_code": "users.login.activation_required",
09-15 13:59:59.968 32405  4511 W System.err: 	"errors": [
09-15 13:59:59.968 32405  4511 W System.err: 		"Account is not yet active, please redirect."
09-15 13:59:59.968 32405  4511 W System.err: 	],

**Comment by PokeAlert** [comment]
You are accounts are not good.You need to create and activate them with a valid mail
