### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Shamazani** [PokeAlert/PokeAlert#152]
Do not login with with your "scanning" accounts in the PokemonGO game with the same phone you using your main playing account. And of course do not login with your main playing account in PokeAlert!

are you saying its best to have a second phone to use PokeAlert to be on the safe side?

/Best Regards

**Comment by lotsobear** [comment]
Your scanning accounts should be just that....scanning accounts.  So you shouldn't really need to ever login with them.  Unless, of course you're also actually playing with them.  Which then in that case, the recommendation is to use a different phone.  This is because the scanning account has a higher chance of getting banned and Niantic may associate your phone with the banned account and could specifically ban your phone.  But if you're just using the scanning accounts for PokeAlert, then less danger in running PokeAlert on the same phone as your main account.

**Comment by Shamazani** [comment]
I have 5 accounts for scanning in PokeAlert, and one main for playing the game, as long as its safe to use them on the same phone i will do that, but if i need a second phone then i need to know

**Comment by PokeAlert** [comment]
@lotsobear explained it correctly

You are "main" is safe unless Niantic starts performing advance statistic stuff to link scanning/main throughs IPs... which would be very stupid/dangerous for them do to :)
