### ISSUE TITLE
Account error?

### ISSUE THREAD

**Issue by WingChroniam** [PokeAlert/PokeAlert#174]
![img_0568](https://cloud.githubusercontent.com/assets/21967669/18812072/889b7c5a-827c-11e6-9416-f89b637308b2.JPG)

I started getting this error for my 5 accounts ever since the last update. What does it mean?

**Comment by Eric678** [comment]
Soft ban of some sort - maybe Nia saying they are watching you!  Happens every few hours to me recently.
@PokeAlert perhaps you could automate rotating a least recently used free account in when this happens as this is what I have to do manually now.

**Comment by PokeAlert** [comment]
@WingChroniam @Eric678 
They are not soft banned. it is just that sometime (after hours usually) the token expires/and or there is timeout connection. and that message is wrongly displayed.

Fix is coming monday night

**Comment by WingChroniam** [comment]
Okay thanks

**Comment by Eric678** [comment]
Interesting - getting more frequent for me and had my main account (in 0.37.1 client) with same symptoms twice yesterday - linked?

**Comment by WingChroniam** [comment]
Wait your MAIN account? Why are you using your main account?

**Comment by Eric678** [comment]
NOT for PA!  everything legit in there but still getting what look like soft bans - none today so could just have been server problems. unusually long times unable to log in when no other users logging problems on outage site. never looked like that before.

**Comment by PokeAlert** [comment]
@Eric678 I had the bad idea in 2.3.15-2 to refactor the scan code AND add IV at the same time.
the scan code refactor needed some more testing. Error where not handled correctly etc... the reason you were saying the spam messages :(

with 2.3.16 I have reverted back the code as it was before because I didn't have time to go backin the rwfactor and prefered playing the safe card. (Error are handled better and more silently)
