### ISSUE TITLE
Please Don't

### ISSUE THREAD

**Issue by roeylange** [PokeAlert/PokeAlert#182]
Dear pokealert dev's,
I am quite new to this website (to be honest i opened my acc just for you guys haha) so exsuse me if I'm being ignorant or dumb. 
I guess you probably know that already but you are helping players world wide A LOT and I'm using your app daily.
I have seen in your last update description that the app will stop working soon bc of the forced update. I will be lost to say the least without your constant help, so i must ask: will there be no more pokealert for good? I'm sure many other people are conserned as well from this subject and will be happy to get some hope from you guys. 
Thanks, and with much appreciation and hope,
Roey.

**Comment by arhi3a** [comment]
I Rly hope that he will find some workaround because without this app playing pokemon wouldn't make sense for me. It will be sitting on lures catching pidgeys or walking around catching pidgeys. 
This app now is almost perfect, i don't remember when i saw so good app, with so caring developer.

**Comment by PokeAlert** [comment]
@roeylange @arhi3a I wont stop maintaing PokeAlert. But unless we can't break 0.39 there isn't much we can do. As soon as we can make request against 0.39 PokeAlert will be the first to Reborn

**Comment by Eric678** [comment]
Breaking safety net auth might take a while - sure it is being worked on in the background now.  Will be a big push when 0.35 api dies.  Thanks for all the work PA!  :-)
Meanwhile make hay!  I am going for every dratini that I can till i go into hibernation when when PA is cut off.

**Comment by roeylange** [comment]
If there is any way we can help be sure to ask because we surely will want to do so.

**Comment by happypokemonhunter** [comment]
Hey Pokealert dev.. I just signed up to tell you that my heart sank when I saw the latest notification that your app may no longer work. I just wanted to say thanks for doing such a great job and making a really helpful tool. I loved Pokemon Go when it first came out, but then Niantic removed the tracking feature and it quickly became stale after running into caterpie after caterpie. Ever since I used your app I was able to find Dragonites, Aerodactlys, Porygons and Snorlaxes with ease, and I have a big collection of them now. And since the latest updates I've been using the IV checker to try and get 100% IVs which is a new fun thing to do. You've made this game so much more fun and I am once again back into Pokemon Go because it has become more accessible again. Unfortunately if it stops working, I don't think I will play Pokemon at all again. Maybe just once a week :( Thank you so much for making this app. It was fun and interesting and I was always excited and impressed to see what was New and improved in every update! Sad to see it potentially come to an end!! Take care and once again Thank you from the bottom of my heart for bringing some joy into my life!!!
