### ISSUE TITLE
Time to expiration is wrong

### ISSUE THREAD

**Issue by niqwilk** [PokeAlert/PokeAlert#241]
Every pokemon that pops up on the scan seems to have 15 minutes to expiration no matter what.  I think this should be an easy fix, but just want people to be aware of the issue.

**Comment by hurtfrog** [comment]
This is known (see twitter). I wonder if there is a way to remember the time area was last scanned with no spawn, and compare it to how long it has been since that scan for an idea of how fresh the spawn might be?

**Comment by hurtfrog** [comment]
or to rescan the area to see if the spawn is still there, or if the 1 minute timer has been returned from the server?

**Comment by Eric678** [comment]
PA should have documented this in the issue comments so we knew what to expect rather than glossing over it and we have to find out by turning up for a mon that has already gone!  Also 30 min spawns cause 2 notifications with current code.  Not every one uses twitter.  Instructions: ignore times till app has been running 15 min then take your scan time off the displayed time to be sure.

**Comment by PokeAlert** [comment]
Twitter is the "main" source of info. it was all over it.
