### ISSUE TITLE
Temporary Ban

### ISSUE THREAD

**Issue by Joaomms** [PokeAlert/PokeAlert#324]
Sorry if this has already been reported by someone.

It's the second time in a couple days that right after I start scanning (with wifi) and get results that few minutes later nothing works inside the game, i.e. can't access gyms nor pokestops and pokemons don't show up. The first time this happened, if I switched from wifi to data it worked again. 
Then I scanned using data and got these problems again, I had to switch to wifi to be able to play. After few hours everything was good again.

Has this happened to anyone else?

Keep up the great work

**Comment by hardknoxni69a** [comment]
This happened the other day buy at this point I spend more time doing good capt chase then playing so niantic pretty much knows where scanning so the put catchall after every request basically

**Comment by arhi3a** [comment]
Q: Why I don't see any Pokemon on map?
A:  Probably your IP has been Soft-Banned (Mostly from 30 minutes to 2h sometimes longer), to check if you were soft banned you can enter the game, if you don't see Pokestops or Gyms you are soft banned, or you can change IP (For some mobile service providers simple restart/airplane mode on/off works) or use Orbot to change your IP if it's static, and scan again. If After changing IP Pokemons are shown on the map that means your IP was Soft-Banned.(edited)
Q: Why my IP got Soft-Banned?
A: Your IP got banned because Niantic detected weird behaviour in game from your IP. It could be too many connections (around 20 is considered safe for now i think), Player that is teleporting long distances, botting activity.
I copied it from PokeAlert Discord

**Comment by Joaomms** [comment]
thanks for those answers
