### ISSUE TITLE
Language change

### ISSUE THREAD

**Issue by piotrrr** [PokeAlert/PokeAlert#334]
Please add the possibility to change the language of the app. New update changed the language to Polish for me and the translation is poorly done, not to mention some text overlaps making it unreadable (i.e. att, def, stamina translations and values).

**Comment by arhi3a** [comment]
Dodanie zmiany języka jest niemożliwe, jeśli chce się zmienić język aplikacji trzeba zmienić język całego telefonu. Co to tekstów nachodzących się na siebie, będzie to naprawione, w każdej wersji językowej się to pojawia przy dłuższych nazwach ataków, w naszej po prostu bardziej bo tłumaczenie jest dłuższe. Jeśli tłumaczenie się nie podoba można stworzyć swoje albo zmienić polskie tutaj: https://github.com/arhi3a/PokeAlert/tree/master/values-pl . Albo napisać do mnie na Discord.

**Comment by piotrrr** [comment]
I appreciate your work, surely the users in Poland will be delighted. But the app worked in English for me prior the update so i don't see how it's 'impossible' to leave us a choice. And i'm not changing the phone language for one app. 

PS. Keeping this in english so more users can benefit from this topic.

**Comment by arhi3a** [comment]
OK, App worked in English before update because Polish language was not in App before. So If there is no translation provided system use default language which is English. But after update Polish was added to the values in app so System detects that there is folder values-pl which is same as your System language PL and it starts using it making whole App shows text from values-pl rather than values (eng). I think it's how mobile systems works.

**Comment by PokeAlert** [comment]
@piotrrr Android doesn't provide a way to change language in app

**Comment by piotrrr** [comment]
@arhi3a thank you for the explanation. This sucks then, because i'd really prefer to use the app with original language.

**Comment by PokeAlert** [comment]
@arhi3a @piotrrr I have fixed the overlapping in the Pokemon info box.
I have also added a new feature to change the language through a dropdown list in the settings
