### ISSUE TITLE
Do nothing while running ditto mode

### ISSUE THREAD

**Issue by hoanhdo** [PokeAlert/PokeAlert#340]
I running pokealert and pokemon go.
After running pokealert ditto mode , my account cannot do nothing. No gym, no pokestop, no sighting.

**Comment by grimley87** [comment]
This also happened to me yesterday. I thought it was a PoGo issue so I uninstalled and reinstalled but it didn't fix the issue. So I stopped playing for 5 hours while at work. After that I opened PAlert and found some Dittos. Opened PoGo and caught the first one. Switched back to PAlert to drive to next ditto with PoGo still on in the background. Once I reached the spot my PoGo wouldn't load any gyms, stops, or pokemon. It took a reboot of my phone for it to work again. Can they tell I'm using both at the same time?

**Comment by arhi3a** [comment]
Q: Why I don't see any Pokemon on map?
A:  Probably your IP has been Soft-Banned (Mostly from 30 minutes to 2h sometimes longer), to check if you were soft banned you can enter the game, if you don't see Pokestops or Gyms you are soft banned, or you can change IP (For some mobile service providers simple restart/airplane mode on/off works) or use Orbot to change your IP if it's static, and scan again. If After changing IP Pokemons are shown on the map that means your IP was Soft-Banned.(edited)
Q: Why my IP got Soft-Banned?
A: Your IP got banned because Niantic detected weird behaviour in game from your IP. It could be too many connections (around 20 is considered safe for now i think), Player that is teleporting long distances, botting activity.
