### ISSUE TITLE
Account stats - what is this ?

### ISSUE THREAD

**Issue by KS71** [PokeAlert/PokeAlert#375]
I have searched for an answer for the "Stats" info on each account, but without any luck.

When looking at the stats I see:
Level ..
Captured: ..
Ball thrown ..
Ball left ..
Km walked ..
Team ..

Does each account walks around, throwing balls and captures pokemons...or what ??

**Comment by arhi3a** [comment]
Real player option/ Ditto mode spins pokestop and throws pokeballs in order to simulate real player behavior/find ditto

**Comment by Pegasuspj** [comment]
But even after I disabled both ditto and real player options, it continues to acquire balls and up level.
Niantic had stated they unnamed people that only used maps, but this means it acts as a bot and THAT is a  forbidden.
Can you fix so no bot action is performed when those 2 actions are disabled? Thanks, your app is the best otherwise.

**Comment by PokeAlert** [comment]
If you disable it wont get new balls
