### ISSUE TITLE
IP soft ban

### ISSUE THREAD

**Issue by LegornSunrise** [PokeAlert/PokeAlert#377]
Greetings!
I have noticed that the max accounts I can use is 25. If I try to use 26 or more in a large area, I get IP soft ban.
Does it happens to anybody else?

**Comment by arhi3a** [comment]
Q: Why I don't see any Pokemon on map?
A:  Probably your IP has been Soft-Banned (Mostly from 30 minutes to 2h sometimes longer), to check if you were soft banned you can enter the game, if you don't see Pokestops or Gyms you are soft banned, or you can change IP (For some mobile service providers simple restart/airplane mode on/off works) or use Orbot to change your IP if it's static, and scan again. If After changing IP Pokemons are shown on the map that means your IP was Soft-Banned.(edited)
Q: Why my IP got Soft-Banned?
A: Your IP got banned because Niantic detected weird behaviour in game from your IP. It could be too many connections (around 20 is considered safe for now i think), Player that is teleporting long distances, botting activity.
