### ISSUE TITLE
Why does the timer and moveset show up only for a very few Pokemon?

### ISSUE THREAD

**Issue by lPing7** [PokeAlert/PokeAlert#439]

**Comment by arhi3a** [comment]
If you are using cache-scan it downloads data sent from other scaners. So if someone is not checking IV only info about pokemon sent to server is pokemon ID and Location. If someone is checking IV information such as Attacks/ IV is also sent to server. That's why not every pokemon have moveset/iv. 
Simmilar thing with timer if someone find correct spawn times, pokemon time left is sent to server but if someone does't have it only location+moveset/iv if checked is being sent to server :)

**Comment by lPing7** [comment]
I'm actually using the regular background scanner.

**Comment by arhi3a** [comment]
If you want to see moveset of pokemon you have to select check iv square because it also checks movesets. About timers they will be shown for most of spawns if you scan same area around 90 times :D

**Comment by lPing7** [comment]
Oh, so the timers are decided based upon spawn point timers?

**Comment by arhi3a** [comment]
more or less, when it's 1:30 minute to despawn server sends that info to game. And because spawn points spawn at same times, if we save it we know when something that spawned there despawns.
