### ISSUE TITLE
Should show whether the pokemon have extra time

### ISSUE THREAD

**Issue by weaqragg** [PokeAlert/PokeAlert#67]
Hi, appreciate your great work on the app.

In the last few version there are _no time returned from the server_ text indicating that the pokemon get an extra time. But _no time returned from the server_ is no longer exist in this update which make us no way to know whether the pokemon get extra time.

I think you can add some text to show the existence of extra time for the pokemon.

**Comment by TFD777** [comment]
@PokeAlert I agree with that. Imagine the situation where a pokemon spawns at 1000m range with 30min timer but the app shows 15mins instead so if I find this pokemon when 20mins are left then the app will show 5mins and i will not go for it because I will think that it is too far when in reality I could still catch it. I would suggest to put a 30min timer on every pokemon with negative tth and then update the timer as soon as the correct tth is received.

**Comment by PokeAlert** [comment]
Done in 2.3.11-1 and up

**Comment by TFD777** [comment]
@PokeAlert you should set this message for the notifications aswell.
