### ISSUE TITLE
Background scanning stopped working

### ISSUE THREAD

**Issue by benjimons** [PokeAlert/PokeAlert#72]
Background scanning doesn't work anymore on version 2.3.11-2. it does work when I leave the app open but the background service doesn't update all all

**Comment by PokeAlert** [comment]
What are the steps to reproduce?

**Comment by inu20** [comment]
I have same problem...
I don't use fixed location, background service on per 1min.. 
sometime it not working. It scan when I open the app.

**Comment by benjimons** [comment]
I think its after the upgrade it wouldnt work until i went into the notifications section and made a change, then after that it worked again in the background.

**Comment by nabakin** [comment]
I have the same issue here.  I don't have fixed location on, all permissions are enabled, notifications are on, but it only automatically scans in the background when the phone isn't asleep and the app is open.

I can tell for sure that it is only scanning when the app is open because the notification in the notification center only changes the "Last update" when the app is open and I only receive notifications about pokemon in my area when the app is open.

**Comment by nabakin** [comment]
I am using the Samsung Galaxy S6 (non edge version) on android version 6.0.1
