### ISSUE TITLE
Lock position for scan schoud disable fix position t second click

### ISSUE THREAD

**Issue by BHMath** [PokeAlert/PokeAlert#73]
I think it would be better if when we click on the lock for the second time no position is selected than a new one in order to dissable the fix location quickly. But if we click a third time on the lock then the background position is locked again.

**Comment by PokeAlert** [comment]
I will change the way the fix thing works because it confuses way to much people at the moment (people complaining the service not working when in fact they didn't chose any locked area)

I will remove the option from the settings and only keep the lock on the Map screen.
And as you suggested it will act has a toggle on/off

**Comment by PokeAlert** [comment]
Fixed in 2.3.11-3
