### ISSUE TITLE
No release notes for 2.3.11-6

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#84]
There is a 2.3.11-6 APK in the download section but no release notes.

**Comment by PokeAlert** [comment]
Hey. 
There is a problem with 2.3.11-5 ONLY affecting certain users.. ! It is caused by the way the Java-API makes the call to the servers to avoid ban.
For certain users (like me an other) it works perfectly. For other it doesn't! Very hard to debug without a stackTrace and logs

This why I have temporarily released -6 which is the exact same version as -5 but with the Java-API downgraded to the previous version
