### ISSUE TITLE
Overlay bugs and suggestions

### ISSUE THREAD

**Issue by TFD777** [PokeAlert/PokeAlert#90]
Hello. First of all, @PokeAlert great work with the overlay, I expected way more bugs for the beta but it is almost perfect. However, I have found some problems that I wanted to mention so it would be easier for you to fix and improve everything.

BUGS:
1. If overlay is openned and you start the background service then the overlay closes itself.
More comments on this: I see that you have already disabled the background service on the new non-beta 2.3.12 release and I think you shouldn't have done this because the background service was working fine with the overlay unless you start manual scans. Also for me the pokemons were showing on both maps. I reverted back to the beta just for the background service on the overlay.
2. When clicking on the found pokemon notifications they are shown on the main app instead of the overlay.
3. When you start the scan and open the overlay without waiting for the scan to finish then the red circles on the main app will freeze and stay forever unless you restart the app.

SUGGESTIONS:
1. Revert the change that prevents the background service working with the overlay.
2. Remove the manual scan button on the overlay when background service is turned on.
3. Show the found pokemons on both maps unless it causes memory problems.

**Comment by PokeAlert** [comment]
Hey thanks for the reports!

1) For technical reasons I'm voluntarily disabling the service when starting the overlay. It 'might' work but I know that several case wont. This is why (for now) I decided to just cut it off

2) yep that needs fixing (this one of the case I was mentioning in 1))

3) humm true, I did stop the scan though, will need to double check this.

For the suggestions:

1) I need to improve the current code so that the overlay, manual scan, background all blend nicely together 

2) Yep

3) Yes the memory is an issue, this is why for the moment I'm just felling ONE view.

**Comment by insanepowerme** [comment]
Bug 3) also happens when you don't use the overlay. This bug is new and wasn't in previous versions. Since I use the app manually a lot of times I am basically not allowed to tab out in this version

**Comment by PokeAlert** [comment]
Hey, I just fixed 3) It was cause by the new "message bus" I implemented. the listener were stopping when the app was minimzed. This caused the "delete" circle message etc.. to be missed :)

**Comment by PokeAlert** [comment]
@TFD777 Most of these + extra fix are released in 2.3.12-1
